const SET_USER = "SET_USER";
const LOGGED_OUT = "LOGGED_OUT";
const PROFILE_UPDATED = "PROFILE_UPDATED";
const TOKEN_REFRESHED = "TOKEN_REFRESHED";
export { LOGGED_OUT, PROFILE_UPDATED, SET_USER, TOKEN_REFRESHED };
